// Keys
export const PRESS_UP = 'PRESS_UP';
export const RELEASE_UP = 'RELEASE_UP';
export const PRESS_DOWN = 'PRESS_DOWN';
export const RELEASE_DOWN = 'RELEASE_DOWN';
export const PRESS_LEFT = 'PRESS_LEFT';
export const RELEASE_LEFT = 'RELEASE_LEFT';
export const PRESS_RIGHT = 'PRESS_RIGHT';
export const RELEASE_RIGHT = 'RELEASE_RIGHT';

// Bike
export const INIT_BIKE = 'INIT_BIKE';
export const UPDATE_BIKE_POSITION = 'UPDATE_BIKE_POSITION';
export const INCREASE_BIKE_VELOCITY = 'INCREASE_BIKE_VELOCITY';
export const DECREASE_BIKE_VELOCITY = 'DECREASE_BIKE_VELOCITY';
export const UPDATE_BIKE = 'UPDATE_BIKE';
export const USE_ENERGY_FUEL = 'USE_ENERGY_FUEL';

// Camera
export const UPDATE_CAMERA_OFFSET = 'UPDATE_CAMERA_OFFSET';

// Game
export const UPDATE_GAME_TIME = 'UPDATE_GAME_TIME';
